### ISSUE TITLE
DB 설계

### ISSUE THREAD

**Issue by moto6** [d-h-k/sidedish#3]
가볍게 시작하시죠 데이터베이스

- 요구조건 분석
    - API 데이터 형태를 참고하여 구조 설계
    - 다이어그램을 그려보고 ERD로 넘어가기
- ERD

**Comment by sallyjellyy** [comment]
[테이블 설계](https://github.com/d-h-k/sidedish/wiki/%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B2%A0%EC%9D%B4%EC%8A%A4-%ED%85%8C%EC%9D%B4%EB%B8%94)
