### ISSUE TITLE
테스트코드 작성

### ISSUE THREAD

**Issue by moto6** [d-h-k/sidedish#36]
테스트코드 작성하기

**Comment by sallyjellyy** [comment]
1. ```java
    @Test
    @DisplayName("1) IoC 컨테이너 정상동작 확인")
    void contextLoads() {} 
2. ```java
    @Test
    @DisplayName("2) Spring Data JDBC MYSQL 연동 확인")
    void readUser() {}
3. ```java
    @Test
    @DisplayName("2) Spring Data JDBC MYSQL 연동 확인")
    void readUser() {}
