### ISSUE TITLE
ASAP 목업 API 

### ISSUE THREAD

**Issue by moto6** [d-h-k/sidedish#4]
- 에자일하게
- interface <@@Repository.java>
  - < Memory@@Repo.java> : 목업 api 던져주고 - 리스트든 뭐든 대충 던져서 만들어주고 
  - < JDBC@@Repo.java> : 천천히 구현하기
- 루카스의 참고 자료 사용해서 URL 정리

- jdbc : 쿼리만들어주는거 대충 다만들어줘서 쉽긴 하지만.. 공부는 해야되고

**Comment by sallyjellyy** [comment]
URL | 기능
-- | --
/best | 베스트 반찬 모두 가져오기
/best/{category_id} | 베스트 반찬 카테고리별 가져오기
/main | 든든한 반찬 내의 모든 아이템 가져오기
/course | 일품요리 내의 모든 아이템 가져오기
/soup | 국, 찌개 내의 모든 아이템 가져오기
/side | 밑반찬 내의 모든 아이템 가져오기
/detail/{item_id} | 아이템 상세 페이지 보기
